apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking
type: Opaque
stringData:
  KEY_VAULT_URL: "__KEY_VAULT_URL__"  # Will be replaced by CI/CD pipeline
  customer-id: "5439090"
  customer-password: "Passw0rd!!"
